# Stolen from https://github.com/envygeeks/jekyll-docker/blob/master/README.md
version: "3"
services:
  site:
    command: jekyll serve --config "_config.yml,_config.dev.yml"
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
